import styles from './MainLayout.module.css'
import Navbar from '../Navbar'
import Head from 'next/head'



export default function MainLayout({children}) {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=5" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar/>

      <main className={styles.main}>

        {children}

      </main>
    </>
  )
}


